version: '3.8'

services:
  back-end:
    build:
      context: backend
    container_name: back-end
    environment:
#      - GOOGLE_APPLICATION_CREDENTIALS=./gilgalwebapp-key-google.json
      #      - FLASK_APP_API_HOST=http://nginx
#      - FLASK_APP_API_HOST=https://web.atom.construction
      - PORT=5000
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "5000:5000"
    command: npm run start
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 312M
networks:
  node-network:
    external: true