FROM node:alpine

# Install OpenSSH client
WORKDIR /usr/src/app

RUN echo "ls"
RUN echo "ls"
RUN echo "ls"
# Install ffmpeg
# Install ffmpeg
#RUN apk add --no-cache
COPY . .
RUN npm install
#RUN npm install -g nodemon
RUN echo "ls"

EXPOSE 5000